x-pfseexbox: &pfseedbox
  profiles:
    - seedbox
    - all
    - mainstay

services:
  jellyfin:
    <<: *pfseedbox
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - UMASK=022
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN_MAIN}
    labels:
      caddy: import reverse_proxy jellyfin {{upstreams 8096}}
    volumes:
      - ${MEDIA_TANK_DIR}/media:/data/media:ro
      - /dev/shm:/cache
      - ${APP_DIR}/jellyfin:/config
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  flaresolverr:
    <<: *pfseedbox
    container_name: flaresolverr
    image: flaresolverr/flaresolverr
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - LOG_LEVEL=info
    restart: unless-stopped
  prowlarr:
    <<: *pfseedbox
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      caddy: import reverse_proxy_auth prowlarr {{upstreams 9696}}
      tinyauth.users: aneekl
    volumes:
      - ${APP_DIR}/prowlarr:/config
    restart: unless-stopped
    depends_on:
      - flaresolverr
  qbittorrent:
    <<: *pfseedbox
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - UMASK=022
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=nord
      - TP_DISABLE_THEME=false
    labels:
      caddy: import reverse_proxy_auth torrent {{upstreams 8080}}
      tinyauth.users: aneekl
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ${MEDIA_TANK_DIR}/torrents:/data/torrents
      - ${APP_DIR}/qbittorrent:/config
    restart: unless-stopped
  sonarr:
    <<: *pfseedbox
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      caddy: import reverse_proxy_auth sonarr {{upstreams 8989}}
      tinyauth.users: aneekl
      tinyauth.allowed: (\/api\/|\/feed\/|\/signalr\/).*
    volumes:
      - ${MEDIA_TANK_DIR}/:/data
      - ${APP_DIR}/sonarr:/config
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
  recyclarr:
    <<: *pfseedbox
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    user: 99:100
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - CRON_SCHEDULE=@daily
      - RECYCLARR_CREATE_CONFIG=true
    volumes:
      - ${APP_DIR}/recyclarr:/config
    restart: unless-stopped
    depends_on:
      - sonarr
  jellyseerr:
    <<: *pfseedbox
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - UMASK=022
      - LOG_LEVEL=info
    labels:
      caddy: import reverse_proxy jellyseerr {{upstreams 5055}}
    volumes:
      - ${APP_DIR}/jellyseerr:/app/config/
    restart: unless-stopped
    depends_on:
      - jellyfin
  fileflows:
    <<: *pfseedbox
    container_name: fileflows
    image: revenz/fileflows:modded-25.04
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok
      - PUID=99
      - PGID=100
      - NVIDIA_VISIBLE_DEVICES=all
    labels:
      caddy: import reverse_proxy_auth fileflows {{upstreams 5000}}
      tinyauth.users: aneekl
    volumes:
      - ${APP_DIR}/fileflows/data:/app/Data
      - ${APP_DIR}/fileflows/logs:/app/Logs
      - /dev/shm:/temp
      - ${MEDIA_TANK_DIR}/torrents:/media/
    restart: unless-stopped
