version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:0.10.0
    container_name: gotosocial
    hostname: gotosocial
    env_file: ./.settings.env
    restart: always
    volumes:
      - ${HOMEDIR}/gotosocial/data/db:/gotosocial/storage

  cloudflared:
    image: cloudflare/cloudflared:2023.7.3
    container_name: cloudflared
    hostname: cloudflared
    command: tunnel --no-autoupdate run --token ${CF_FEDIVERSE_TOKEN}
    restart: always
    depends_on:
      - gotosocial
